#!/bin/bash

. ./util/process.u
. ./util/os.u

basepath=$(cd `dirname .`; pwd)
#echo $basepath
scriptpath="$basepath:$basepath/applist/:$basepath/bin/:$basepath/case/:$basepath/config/:$basepath/logutil/:$basepath/mon/:$basepath/parser/:$basepath/prebuilt_tools/:$basepath/tools/:$basepath/test/:$basepath/util/"

echo "PATH=$scriptpath:\${PATH}" >> ~/.bashrc
echo "export SCRIPT_ROOT=${basepath}" >> ~/.bashrc

# set my bash env
(cat <<EOF
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;33m\]\u\[\033[00m\]\[\033[01;31m\][\[\033[00m\]\[\033[04;32m\]\t\[\033[00m\]\[\033[01;31m\]]\[\033[00m\]\[\033[01;33m\]\h:\[\033[00m\]\[\033[01;34m\]\w\[\033[00m\]\n\[\033[45;37m\]#\[\033[0m\]  '
EOF
) >> ~/.bashrc

echo "alias aShell='bash --rcfile \${SCRIPT_ROOT}/tbox/.myAndDevice.rc'" >> ~/.bashrc
echo "alias as='aShell'" >> ~/.bashrc
echo -e "\033[41;37m" Please restart your terminal and Work in your New environment "\033[0m"

#$terminal_execfile -t "MY Shell" -h always -w max kill_others &

# prepare some python environment
# python lib repo: http://www.lfd.uci.edu/~gohlke/pythonlibs