#!/bin/bash

function showstr_fred {
	echo -e "\033[31m"$*"\033[0m"
}

function showstr_fyellow {
	echo -e "\033[33m"$*"\033[0m"
}

function showstr_fblue {
	echo -e "\033[34m"$*"\033[0m"
}

function showstr_fgreen {
	echo -e "\033[32m"$*"\033[0m"
}

function red {
	showstr_fred $*
}

function blue {
	showstr_fblue $*
}

function yellow {
	showstr_fyellow $*
}

function green {
	showstr_fgreen $*
}

function space {
	local i
	if [ ! -z $1 ];then
		for ((i=0;i<$1;i=$i+1))
		do
			echo -e " \c";
		done
	fi
}

if [ ! -n "$1" ];then
	red "Please Run this script with your sudo passwd"
	echo
	green "$0 sudopasswd"
	echo
	exit
fi

passwd=$1

####install flag####
prepare_install=true
common_install=true
deb_install=false
android_install=true
latext_install=true
opencv_install=true
iotool_install=true
vim_install=true
pylib_install=true
####install flag####

inx=0
failed_info[$inx]="List all failed installing, you should install them manual!"
function inx_pp {
	inx=`expr $inx + 1`
}

function record_failinfo {
	inx_pp
	failed_info[$inx]=$1
}

function apt_fix {
	echo $passwd |sudo -S apt-get -f -y install
}

##update source list
echo $passwd |sudo -S apt-get update

##prepare for installing start
if $prepare_install;then
	blue "Start install some prepared packages....."
	for package in git gitk libqtwebkit4 libqt4-opengl libsdl1.2debian lib32ncurses5 lib32z1 cifs-utils vlc;
	do

		echo $passwd |sudo -S apt-get install -y $package	
		if [ $? -ne 0 ];then
			red "$package install fail"
			apt_fix
			##reinstall it again start
			echo $passwd |sudo -S apt-get install -y $package	
			if [ $? -ne 0 ];then
				red "$package install fail"
				record_failinfo $package
				echo
			else
				green "$package install sucess"
				echo
			fi
			##reinstall it again end
			echo
		else
			green "$package install sucess"
			echo
		fi

	done
	blue "End of install prepare packages....."
	echo
fi
##prepare for installing end

##common used start
if $common_install;then
	blue "Start install some common packages....."
	for package in terminator fcitx redshift redshift-gtk uget rdesktop shutter wxhexeditor wine;
	do
	which $package
	if [ $? -ne 0 ];then
		echo $passwd |sudo -S apt-get install -y $package	
		if [ $? -ne 0 ];then
			red "$package install fail"
			apt_fix
			##reinstall it again start
			echo $passwd |sudo -S apt-get install -y $package	
			if [ $? -ne 0 ];then
				red "$package install fail"
				record_failinfo $package
				echo
			else
				green "$package install sucess"
				echo
			fi
			##reinstall it again end
			echo
		else
			green "$package install sucess"
			echo
		fi
	fi
	done
	blue "End of install common packages....."
	echo
fi
##common used end

##deb install start
if $deb_install;then
	blue "Start install some deb packages....."
	for deb in `ls ~/data/ubuntu_env/install/deb/*deb`
	do
		echo $passwd |sudo -S dpkg -i $deb
		if [ $? -ne 0 ];then
			red "$deb install fail"
			apt_fix
			##reinstall it again start
			echo $passwd |sudo -S dpkg -i $deb
			if [ $? -ne 0 ];then
				red "$deb install fail"
				record_failinfo $deb
				echo
			else
				green "$deb install sucess"
				echo
			fi
			##reinstall it again end
			echo
		else
			green "$deb install sucess"
			echo
		fi
	done
	blue "End of install deb related packages....."
	echo
fi
##deb install end

##install for android compile start####
if $android_install;then
	blue "Start install some Android related packages....."
	for package in git-core gnupg flex bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses5-dev x11proto-core-dev libx11-dev lib32z-dev ccache libgl1-mesa-dev libxml2-utils xsltproc unzip android-tools-adb;
	do
	which $package
	if [ $? -ne 0 ];then
		echo $passwd |sudo -S apt-get install -y $package	
		if [ $? -ne 0 ];then
			red "$package install fail"
			apt_fix
			##reinstall it again start
			echo $passwd |sudo -S apt-get install -y $package	
			if [ $? -ne 0 ];then
				red "$package install fail"
				record_failinfo $package
				echo
			else
				green "$package install sucess"
				echo
			fi
			##reinstall it again end
			echo
		else
			green "$package install sucess"
			echo
		fi
	fi
	done
	blue "End of install Android related packages....."
	echo
fi
##install for android compile end####

##install latex related start####
if $latext_install;then
	blue "Start install some latex related packages....."
	for package in texlive-xetex latex-cjk-all texmaker fonts-wqy-microhei;
	do
	which $package
	if [ $? -ne 0 ];then
		echo $passwd |sudo -S apt-get install -y $package	
		if [ $? -ne 0 ];then
			red "$package install fail"
			apt_fix
			##reinstall it again start
			echo $passwd |sudo -S apt-get install -y $package	
			if [ $? -ne 0 ];then
				red "$package install fail"
				record_failinfo $package
				echo
			else
				green "$package install sucess"
				echo
			fi
			##reinstall it again end
			echo
		else
			green "$package install sucess"
			echo
		fi
	fi
	done
	blue "End of install latex related packages....."
	echo
fi
##install latex related end####

##install opencv related start####
if $opencv_install;then
	blue "Start install some opencv related packages....."
	for package in build-essential checkinstall cmake pkg-config yasm git gfortran libjpeg8-dev libjasper-dev libpng12-dev libtiff5-dev libavcodec-dev libavformat-dev libswscale-dev libdc1394-22-dev libxine2-dev libv4l-dev libgstreamer0.10-dev libgstreamer-plugins-base0.10-dev qt5-default libgtk2.0-dev libtbb-dev libatlas-base-dev libfaac-dev libmp3lame-dev libtheora-dev libvorbis-dev libxvidcore-dev libopencore-amrnb-dev libopencore-amrwb-dev x264 v4l-utils libprotobuf-dev protobuf-compiler libgoogle-glog-dev libgflags-dev libgphoto2-dev libeigen3-dev libhdf5-dev doxygen;
	do

		echo $passwd |sudo -S apt-get install -y $package	
		if [ $? -ne 0 ];then
			red "$package install fail"
			apt_fix
			##reinstall it again start
			echo $passwd |sudo -S apt-get install -y $package	
			if [ $? -ne 0 ];then
				red "$package install fail"
				record_failinfo $package
				echo
			else
				green "$package install sucess"
				echo
			fi
			##reinstall it again end
			echo
		else
			green "$package install sucess"
			echo
		fi

	done
	blue "End of install vim related packages....."
	echo
fi
##install opencv related end####

##install iotool related start####
if $iotool_install;then
	blue "Start install some io realted packages....."
	for package in blktrace;
	do

		echo $passwd |sudo -S apt-get install -y $package	
		if [ $? -ne 0 ];then
			red "$package install fail"
			apt_fix
			##reinstall it again start
			echo $passwd |sudo -S apt-get install -y $package	
			if [ $? -ne 0 ];then
				red "$package install fail"
				record_failinfo $package
				echo
			else
				green "$package install sucess"
				echo
			fi
			##reinstall it again end
			echo
		else
			green "$package install sucess"
			echo
		fi

	done

	blue "End of install io related packages....."
	echo
fi
##install iotool related end####

##install vim related start####
if $vim_install;then
	blue "Start install some vim related packages....."
	for package in vim vim-scripts vim-doc vim-addon-manager ctags cscope;
	do

		echo $passwd |sudo -S apt-get install -y $package	
		if [ $? -ne 0 ];then
			red "$package install fail"
			apt_fix
			##reinstall it again start
			echo $passwd |sudo -S apt-get install -y $package
			if [ $? -ne 0 ];then
				red "$package install fail"
				record_failinfo $package
				echo
			else
				green "$package install sucess"
				echo
			fi
			##reinstall it again end
			echo
		else
			green "$package install sucess"
			echo
		fi

	done

	for componant in omnicppcomplete taglist winmanager minibufexplorer;
	do
		vim-addons install $componant
	done

	blue "End of install vim related packages....."
	echo
fi
##install vim related end####

##install python lib related start####
if $pylib_install;then
	blue "Start install python related....."
	for package in python-pip;
	do

		echo $passwd |sudo -S apt-get install -y $package	
		if [ $? -ne 0 ];then
			red "$package install fail"
			apt_fix
			##reinstall it again start
			echo $passwd |sudo -S apt-get install -y $package
			if [ $? -ne 0 ];then
				red "$package install fail"
				record_failinfo $package
				echo
			else
				green "$package install sucess"
				echo
			fi
			##reinstall it again end
			echo
		else
			green "$package install sucess"
			echo
		fi

	done

	pip install --upgrade pip
	echo

	for componant in matplotlib numpy plotly configparser pandas;
	do
		pip install $componant
	done

	blue "End of install python related....."
	echo
fi
##install python lib related end####

##summary all failed info start###
if [ $inx -gt 0 ];then
	red ${failed_info[0]}
	for ((i=1;i<=$inx;i=$i+1))
	do
		space 4
		red "${failed_info[$i]} install fail"
	done
fi
##summary all failed info start###
