#!/bin/bash

. ./util/process.u
. ./util/os.u

basepath=$(cd `dirname .`; pwd)
#echo $basepath

(cat <<EOF

## Custom Start ##
scriptpath="$basepath:$basepath/applist/:$basepath/bin/:$basepath/case/:$basepath/config/:$basepath/logutil/:$basepath/mon/:$basepath/parser/:$basepath/prebuilt_tools/:$basepath/tools/:$basepath/test/:$basepath/util/:$basepath/eMMC_Test/bin/"
PATH=\${scriptpath}:\${PATH}
export SCRIPT_ROOT=${basepath}

ASHELL_ROOT=\$SCRIPT_ROOT/tbox/
ASHELL_VERSION=1.0.1
export ASHELL_ROOT
export ASHELL_VERSION

#eval "dircolors -b \$SCRIPT_ROOT/tbox/.DIR_COLORS"
LS_COLORS=\$(dircolors -b \$ASHELL_ROOT/.DIR_COLORS|awk -F "'" 'NR==1{print \$2}')
export LS_COLORS

alias ls='ls -F --color=auto --show-control-chars'
alias evelog='adb logcat -b events'
alias logcat='adb logcat'
alias getprop='adb shell getprop'
alias setprop='adb shell setprop'
alias dropcache='adb shell echo 3 > //proc/sys/vm/drop_caches'
alias la='ls -la'
alias ll='ls -l'
alias lla='ls -la'
alias lh='ls -lh'
alias l='lla'
alias lls='l'
alias grep='grep --color'
alias exit="date > \$ASHELL_ROOT/.last_logout_time;reset;exit"
#alias vim='vim -u \$ASHELL_ROOT/conf/.viminfo'
alias vi='vim -u \$SCRIPT_ROOT/tbox/conf/_vimrc'
alias activate='source activate'
alias rm='rm -rf'
alias aShell='bash --rcfile \${SCRIPT_ROOT}/tbox/.myAndDevice.rc'
alias as='aShell'
alias cdroot='cd \${SCRIPT_ROOT}'
alias cls='printf "\033c"'
alias pelf='python \${SCRIPT_ROOT}/py/parser/elf.parser'

alias lx="ls -l|awk '{if(NR>1) printf(\"%s\t0x%x\n\", \$0,\$5)}'"

git config --global core.editor vi
git config --global core.quotepath false

stty echo
#PYTHON2_PATH="/$(echo $PYTHON2|sed 's/\\/\//g'|sed 's/://g')"
#PYTHON3_PATH="/$(echo $PYTHON3|sed 's/\\/\//g'|sed 's/://g')"
#export PATH=\${PYTHON3_PATH}:\${PYTHON3_PATH}/Scripts/:"\${PATH}":"\$ASHELL_ROOT/tools/"
export PATH="\${PATH}":"\$ASHELL_ROOT/tools/"

#####start define complete#########
for tabfile in \$(find -L \$ASHELL_ROOT/conf/ -name *tab*)
do
	. \$tabfile
done
#####end complete#########

###set java env start###                                                                                                                          
##java 10.0.1
export JAVA_HOME=/home/wisen/data/java/jdk-10.0.1
export JRE_HOME=/home/wisen/data/java/jre-10.0.1
##java 1.8.0_172
#export JAVA_HOME=/home/wisen/data/java/jdk1.8.0_172
#export JRE_HOME=/home/wisen/data/java/jre1.8.0_172

export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib  
export PATH=\${JAVA_HOME}/bin:\${PATH}
###set java env end###

###Mount sdb2 start###
cat /proc/mounts | grep "\/dev\/sdb2" > /dev/null
if [ $? -ne 0 ];then
sudo -S mount -t ntfs /dev/sdb2 /home/wisen/data <<MMM
56630873
MMM
fi

if [ $? -eq 0 ] 
then
    echo "Mount \/dev\/sdb2 sucess" > /dev/null
else
    echo -e "\033[31m Mount \/dev\/sdb2 fail..  \033[0m"
fi
###Mount sdb2 end###

###Mount reallytek start###
cat /proc/mounts | grep "//192.168.1.71/reallytek/" > /dev/null
if [ $? -ne 0 ];then
sudo -S mount -t cifs -o username="wanbin.wang",pass="Bb123456" //192.168.1.71/reallytek/ /home/wisen/smb/71/reallytek/ <<AAA
56630873
AAA
fi

if [ $? -eq 0 ]
then
    echo "Mount reallytek sucess" > /dev/null
else
    echo -e "\033[31m Mount reallytek fail..  \033[0m"
fi
###Mount reallytek end###

###Mount Transsionsharing start###
cat /proc/mounts | grep ""//192.168.1.75/Transsionsharing/ > /dev/null
if [ $? -ne 0 ];then
sudo -S mount -t cifs -o username="wanbin.wang",pass="Bb123456" //192.168.1.75/Transsionsharing/ /home/wisen/smb/75/Transsionsharing <<BBB
56630873
BBB
fi

if [ $? -eq 0 ]
then
    echo "Mount Transsionsharing sucess" > /dev/null
else
    echo -e "\033[31m Mount Transsionsharing fail..  \033[0m"
fi
###Mount Transsionsharing end###

###set cuda path start###
export CUDA_HOME=/usr/local/cuda-9.2/bin
export PATH=\${PATH}:\${CUDA_HOME}/bin
export LD_LIBRARY_PATH=/usr/local/cuda-9.2/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
###set cuda path end###

PS1='\[\033[01;33m\]\u\[\033[00m\]\[\033[01;31m\][\[\033[00m\]\[\033[04;32m\]\t\[\033[00m\]\[\033[01;31m\]]\[\033[00m\]\[\033[35;40m\] aShell \[\033[00m\]\[\033[01;34m\]\w\[\033[00m\]\n\[\033[45;37m\]$\[\033[0m\]  '

#export HOME=\$ASHELL_ROOT/home/
#cd \$HOME
cd ~/test

## Custom END ##
EOF
) >> ~/.bashrc

echo -e "\033[41;37m" Please restart your terminal and Work in your New environment "\033[0m"

#$terminal_execfile -t "MY Shell" -h always -w max kill_others &

# prepare some python environment
# python lib repo: http://www.lfd.uci.edu/~gohlke/pythonlibs
