#!/bin/bash

echo "write"

test_cycles=20
tmp_file=tmp".$(date +%s)"".lmddtst"
result_file=lmddtst".$(date +%s)"".log"

str=""
for sz in 8k 32k 64k 128k 512k 2m 8m 32m 64m 128m 256m
do
    echo $sz | tee -a ${result_file}
    echo -e "data\tsdcard" | tee -a ${result_file}
    #data_sum=0
    #sdcard_sum=0
    for((i=1;i<=$test_cycles;i++))
    do
        data_speed=$(adb shell //data/lmdd if=internal of=//data/dumb move=$sz fsync=1|awk '{print $6}')
        sdcard_speed=$(adb shell //data/lmdd if=internal of=//sdcard/dumb move=$sz fsync=1|awk '{print $6}')
        echo -e "${data_speed}\t${sdcard_speed}" | tee -a ${tmp_file}
        #data_sum=$((data_sum+data_speed))
        #sdcard_sum=$((sdcard_sum+sdcard_speed))
    done
    #echo -e "$(($data_sum/$test_cycles))\t$(($sdcard_sum/$test_cycles))"
    #cat ${tmp_file} |awk -v count=$test_cycles '{s1=s1+$1;s2=s2+$2;} END{printf("%0.2f\t%0.2f", s1/count, s2/count);}' | tee -a ${result_file}
    str=$str$(cat ${tmp_file} |awk -v count=$test_cycles '{s1=s1+$1;s2=s2+$2;} END{printf("%0.2f\t%0.2f", s1/count, s2/count);}')"\t"
    echo | tee -a ${result_file}
done
echo -e "avg:\t"$str
echo
echo "read"
for sz in 8k 32k 64k 128k 512k 2m 8m 32m 64m 128m 256m
do
    echo -e "data\tsdcard" | tee -a ${result_file}
    for((i=1;i<=$test_cycles;i++))
    do
        adb shell "echo 3 > //proc/sys/vm/drop_caches"
        data_speed=$(adb shell //data/lmdd if=//data/dumb of=internal move=$sz fsync=1|awk '{print $6}')
        sdcard_speed=$(adb shell //data/lmdd if=//sdcard/dumb of=internal move=$sz fsync=1|awk '{print $6}')
        echo -e "${data_speed}\t${sdcard_speed}" | tee -a ${result_file}
    done
    echo | tee -a ${result_file}
done