#!/bin/bash

prefix=$ASHELL_ROOT/conf/tr_systrace_prefix
postfix=$ASHELL_ROOT/conf/tr_systrace_postfix

infile=$1
outfile=$1.html

cat $prefix > $outfile
cat $infile >> $outfile
cat $postfix >> $outfile