#!/bin/bash
. color.u

last_login_time=`cat $ASHELL_ROOT/.last_login_time|awk 'NR==1{print $0}'`
da=`sh clac_date`

space 18;yellow '_oo0oo_'
space 17;yellow '088888880'
space 17;yellow '88" . "88'
space 17;yellow '(| -_- |)\c'; echo "      Last Login: "$last_login_time
space 18;yellow '0\ = /0\c'; echo "       Lunar time: "$da;
space 15;yellow "___/'---'\___"
space 13;yellow ".'\\\\|       |//'."
space 12;yellow "/ \\\\||   :   ||// \\"
space 11;yellow "/_ ||||  -:-  |||| _\\"
space 10;yellow "|  | \\\\\\\\  -  //// |  |"
space 10;yellow "| \\_|  ''\\---/'' |_/  |"
space 10;yellow "\\ .-\\__   '-'   __/-. /"
space 8;yellow "___'. .'  /--.--\\  '. .'___"
space 5;yellow ".\"\"  '< '.___\\_<|>_/___.' >'  \"\"."
space 5;yellow "| | :  '-\\'.:'\\ _ /':.'/-'  : | |"
space 5;yellow "\\ \\  '_.  \\_ __\\ /__ _/  .-'  / /"
space 1;yellow "====='-.____'.__ \_____/__.-'____.-'====="
space 18;yellow "'=---='"
yellow "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
yellow "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
