#!/bin/bash

. color.u

zygote_pid=`adb shell ps -t|grep zygote|awk '{print $2}'`
if [ -z $zygote_pid ];then
    red "Cannot find zygote process!"
    exit
fi

system_server_pid=`adb shell ps -t|grep system_server|awk -v zpid="$zygote_pid" '{if($3==zpid) print $2;}'`
if [ -z $system_server_pid ];then
    red "Cannot find system_server process!"
    exit
fi

adb shell ps -t|grep $system_server_pid|awk -v spid="$system_server_pid" '{
                                                if($3==spid && $9=="InputDispatcher") tInputDispatcher=$2;
                                                if($3==spid && $9=="InputReader") tInputReader=$2;
                                                if($3==spid && $9=="android.ui") tandroid_ui=$2;
                                            }

                                            END{
                                                printf("  system_server(%d)\n", spid);
                                                printf("    InputDispatcher(%d)\n", tInputDispatcher);
                                                printf("    InputReader(%d)\n", tInputReader);
                                                printf("    android.ui(%d)\n", tandroid_ui);
                                            }'

function get_related_threadid {
    _tmp_apk_pid=$1
    adb shell ps -t|grep $_tmp_apk_pid|awk -v apid="$_tmp_apk_pid" 'BEFORE{
                                            line=1;
                                         }

                                         {
                                           if($2==apid){printf("  %s(%d)\n", $9, apid);}
                                           if($3==apid && $9=="RenderThread"){printf("    RenderThread(%d)\n", $2);}
                                           if($3==apid && $9=="hwuiTask1"){printf("    hwuiTask1(%d)\n", $2);}
                                           if($3==apid && $9=="hwuiTask2"){printf("    hwuiTask2(%d)\n", $2);}
                                        }'
}

apk_pid=`adb shell ps |grep com|awk '{print $2}'`
for i in $apk_pid
do
    get_related_threadid $i
done