#!/bin/bash

data_avail=`adb shell df -k|awk '/\/data/{if(match($6,"/data"))print $4;}'`

count_32k=0
count_32k=$(($data_avail/32/5))

count_64k=0
count_64k=$(($data_avail/64/5))

count_128k=0
count_128k=$(($data_avail/128/5))

count_256k=0
count_256k=$(($data_avail/256/5))

count_512k=0
count_512k=$(($data_avail/512/5))

echo "$count_32k $count_64k $count_128k $count_256k $count_512k "

cloop32k=$(($count_32k/100))
addcount32k=200
delcount32k=100
echo "32k: $cloop32k,$addcount32k,$delcount32k"

cloop64k=$(($count_64k/100))
addcount64k=200
delcount64k=100
echo "64k: $cloop64k,$addcount64k,$delcount64k"

cloop128k=$(($count_128k/100))
addcount128k=200
delcount128k=100
echo "128k: $cloop128k,$addcount128k,$delcount128k"

cloop256k=$(($count_256k/100))
addcount256k=200
delcount256k=100
echo "256k: $cloop256k,$addcount256k,$delcount256k"

cloop512k=$(($count_512k/100))
addcount512k=200
delcount512k=100
echo "512k: $cloop512k,$addcount512k,$delcount512k"

echo "#####################"

dirpath=/data/tmp/
(cat <<EOF
32k: $cloop32k,$addcount32k,$delcount32k

for k in \$(seq 1 1 $cloop32k);do
for i in \$(seq 1 1 $addcount32k);do dd if=/dev/urandom of=$dirpath\$((\$RANDOM*1000+\$RANDOM))_32k.dat bs=32k count=1;done
file_list=\`ls $dirpath*_32k.dat\`;j=0;for file in \$file_list;do rm -f \$file;j=\`expr \$j + 1\`;if [ \$j -gt $delcount32k ];then break;fi;done
done
EOF
)
echo

(cat <<EOF
64k: $cloop64k,$addcount64k,$delcount64k

for k in \$(seq 1 1 $cloop64k);do
for i in \$(seq 1 1 $addcount64k);do dd if=/dev/urandom of=$dirpath\$((\$RANDOM*1000+\$RANDOM))_64k.dat bs=64k count=1;done
file_list=\`ls $dirpath*_64k.dat\`;j=0;for file in \$file_list;do rm -f \$file;j=\`expr \$j + 1\`;if [ \$j -gt $delcount64k ];then break;fi;done
done
EOF
)
echo

(cat <<EOF
128k: $cloop128k,$addcount128k,$delcount128k

for k in \$(seq 1 1 $cloop128k);do
for i in \$(seq 1 1 $addcount128k);do dd if=/dev/urandom of=$dirpath\$((\$RANDOM*1000+\$RANDOM))_128k.dat bs=128k count=1;done
file_list=\`ls $dirpath*_128k.dat\`;j=0;for file in \$file_list;do rm -f \$file;j=\`expr \$j + 1\`;if [ \$j -gt $delcount128k ];then break;fi;done
done
EOF
)
echo

(cat <<EOF
256k: $cloop256k,$addcount256k,$delcount256k

for k in \$(seq 1 1 $cloop256k);do
for i in \$(seq 1 1 $addcount256k);do dd if=/dev/urandom of=$dirpath\$((\$RANDOM*1000+\$RANDOM))_256k.dat bs=256k count=1;done
file_list=\`ls $dirpath*_256k.dat\`;j=0;for file in \$file_list;do rm -f \$file;j=\`expr \$j + 1\`;if [ \$j -gt $delcount256k ];then break;fi;done
done
EOF
)
echo

(cat <<EOF
512k: $cloop512k,$addcount512k,$delcount512k

for k in \$(seq 1 1 $cloop512k);do
for i in \$(seq 1 1 $addcount512k);do dd if=/dev/urandom of=$dirpath\$((\$RANDOM*1000+\$RANDOM))_512k.dat bs=512k count=1;done
file_list=\`ls $dirpath*_512k.dat\`;j=0;for file in \$file_list;do rm -f \$file;j=\`expr \$j + 1\`;if [ \$j -gt $delcount512k ];then break;fi;done
done
EOF
)


