#!/bin/bash

logfile=write_emmc.log

echo "####################64k##############################"|tee $logfile
data_avail=`adb shell df -k|awk '/\/data/{if(match($6,"/data"))print $4;}'`
#data_avail=$1
echo "$data_avail"|tee -a $logfile

count_64k=0
count_64k=$(($data_avail/64))
echo "count_64k=$count_64k"|tee -a $logfile

#for i in {1..$count_64k};
for i in $(seq 1 1 $count_64k)
do
    adb shell "dd if=//dev/urandom of=//data/tmp/${RANDOM}_64k.dat bs=64k count=1"
    echo $i|tee -a $logfile
done;

#delete 30% of the count_64k
count_64k=``
delete_count=0
delete_count=$(($count_64k*30))
delete_count=$(($delete_count/100))
echo "delete_count=$delete_count"|tee -a $logfile

file_list=`ls *_64k`
j=0
for file in $file_list;do
    echo "$j, rm -f $file"|tee -a $logfile
    rm -f $file
	j=`expr $j + 1`
    if [ $j -gt $delete_count ];then
        break;
    fi
done

####################128k##############################
data_avail=`adb shell df -k|awk '/\/data/{if(match($6,"/data"))print $4;}'`
count_128k=0
count_128k=$(($data_avail/128))
echo "count_128k=$count_128k"|tee -a $logfile
for i in $(seq 1 1 $count_128k)
do
    adb shell "dd if=//dev/urandom of=//data/tmp/${RANDOM}_128k.dat bs=128k count=1"
    echo $i|tee -a $logfile
done;

file_list=`ls *_64k`
j=0
for file in $file_list;do
    echo "$j, rm -f $file"|tee -a $logfile
    rm -f $file
	j=`expr $j + 1`
    if [ $j -gt $delete_count ];then
        break;
    fi
done

####################256k##############################
data_avail=`adb shell df -k|awk '/\/data/{if(match($6,"/data"))print $4;}'`
count_256k=0
count_256k=$(($data_avail/256))
echo "count_256k=$count_256k"|tee -a $logfile
for i in $(seq 1 1 $count_256k)
do
    adb shell "dd if=//dev/urandom of=//data/tmp/${RANDOM}_256k.dat bs=256k count=1"
    echo $i|tee -a $logfile
done;

