#!/bin/bash

function dumpsys_help() {
cat <<EOF
	usage: 
       dumpsys [--all] [-t TIMEOUT] [--help | -l | --skip SERVICES | SERVICE [ARGS]]
		 --all: To dump all services
         --help: shows this help
         -l: only list services, do not dump them
         -t TIMEOUT: TIMEOUT to use in seconds instead of default 10 seconds
         --skip SERVICES: dumps all services but SERVICES (comma-separated list)
         SERVICE [ARGS]: dumps only service SERVICE, optionally passing ARGS to it
EOF
}

if [ $# -eq 0 ];then
	dumpsys_help
	exit;
fi

if [ $1 == "--help" ];then
	dumpsys_help;
	exit
fi

if [ $1 == "--all" ];then
	adb shell dumpsys
	exit
fi

adb shell dumpsys $*
