#!/bin/bash

function getprop_help() {
	echo "Total properties: "$(adb shell getprop|wc -l)
	echo "Category: "$(adb shell getprop|sed 's/\[\|\]\|://g'|awk -F "." '{print $1}'|uniq|wc -l)
	adb shell getprop|sed 's/\[\|\]\|://g'|awk -F "." '{print $1}'|uniq|awk '{printf NR%6?$NF"\t":$NF"\n"}'
}

if [ $# -gt 0 ];then
	if [ $1 == "-l" ];then
		getprop_help;
		exit
	fi

	if [ $1 == "-h" ];then
		getprop_help;
		exit
	fi

	if [ $1 == "--help" ];then
		getprop_help;
		exit
	fi

	if [ $1 == "?" ];then
	     getprop_help;
	    exit
	fi
fi

adb shell getprop $*
