#!/bin/bash
# Author: wisen_wang
# Description: make for recording Android OS memory info
# Date: 2017-02-13

. color.u
. devices_var.u

#dev_SN=($(adb devices|sed '/^$/d'|awk '{if(NR>1) printf("%s\n", $1);}'))

#yellow "INDEX\tProduct\t\t\tSN"
#for ((j=0;j<${#dev_SN[@]};j=$j+1))
#do
#	#echo ${dev_SN[$j]}
#	dev_Product[$j]=`adb -s ${dev_SN[$j]} shell getprop ro.product.device|awk '{if(NR==1) print $0;}'`
#	dev_Index[$j]=$j
#	green "${dev_Index[$j]}\t${dev_Product[$j]}\t\t${dev_SN[$j]}"
#done

#red_white "Please enter the Device Index:"
#read device_ind
#device_sn=${dev_SN[$device_ind]}
#red "Please confirm your chose: [$device_ind] $device_sn ${dev_Product[$device_ind]}"
#read


echo "******************************"
file_list=`ls *apk`
apk_num=`ls *apk|wc -l`
#install_flag=false

echoc "There are total ";redc $apk_num; space 1; echo "Apks:"
echo
echo

i=1;
for file in $file_list;do
    #echo $file
    suffix=`echo $file|awk -F . '{print $NF}'`
	#echo suffix=$suffix;
	if [ $suffix == "apk" ];then
		greenc "####Install the"; space 1; redc $i; greenc "th apk:";space 1; yellow $file;
		date "+%Y-%m-%d %H:%M:%S"
		adb -s $device_sn install -r $file
		i=$(($i+1))
	fi
done
