#!/bin/bash

## $1: systrace file(the trace should be enable Disk IO and Android Disk IO)

tracefile=$1

totalread=`grep "android_fs_dataread_start" $tracefile |awk -F "," '{print $3}'|awk 'BEGIN{sum=0} {sum=sum+$2;} END{print sum/1024}'`
totalwrite=`grep "android_fs_datawrite_start" $tracefile |awk -F "," '{print $3}'|awk 'BEGIN{sum=0} {sum=sum+$2;} END{print sum/1024}'`

parsertime=`date "+%Y%m%d%H%M%S"`

###### parser read io###########
read_tmp_appname_file=read.$parsertime.tmpappname
read_tmp_data_file=read.$parsertime.tmpdata
read_result_file=read.$parsertime.result
grep "android_fs_dataread_start" $tracefile|awk -F ":" '{print $3}'|sed 's/,//g'|awk '$2~/^\/./{print $2}'|sort|uniq > $read_tmp_appname_file
grep "android_fs_dataread_start" $tracefile|awk -F ":" '{print $3}'|sed 's/,//g'|awk '$2~/^\/./{print $6,$2}'|sort > $read_tmp_data_file

echo -e "\033[34m" Total read: $totalread "\033[0m"
while read appname
do
	#echo $appname
	#cat $read_tmp_data_file|awk -v a_app="$appname" 'BEGIN{sum=0;} $0~a_app{sum=sum+$2;} END{print a_app,sum}' |tee -a $read_result_file
	cat $read_tmp_data_file | grep "$appname$" | awk -v a_app="$appname" '{sum=sum+$1} END{print a_app,sum/1024}' |tee -a $read_result_file
done < $read_tmp_appname_file

echo
###### parser write io###########
write_tmp_appname_file=write.$parsertime.tmpappname
write_tmp_data_file=write.$parsertime.tmpdata
write_result_file=write.$parsertime.result
grep "android_fs_datawrite_start" $tracefile|awk -F ":" '{print $3}'|sed 's/,//g'|awk '$2~/^\/./{print $2}'|sort|uniq > $write_tmp_appname_file
grep "android_fs_datawrite_start" $tracefile|awk -F ":" '{print $3}'|sed 's/,//g'|awk '$2~/^\/./{print $6,$2}'|sort > $write_tmp_data_file

echo -e "\033[34m" Total write: $totalwrite "\033[0m"
while read appname
do
	#echo $appname
	#cat $write_tmp_data_file|awk -v a_app="$appname" 'BEGIN{sum=0;} $0~a_app{sum=sum+$2;} END{print a_app,sum}' |tee -a $write_result_file
	cat $write_tmp_data_file | grep "$appname$" | awk -v a_app="$appname" '{sum=sum+$1} END{print a_app,sum/1024}' |tee -a $write_result_file
done < $write_tmp_appname_file

#rm $read_tmp_appname_file $read_tmp_data_file $write_tmp_appname_file $write_tmp_data_file