#!/bin/bash

. os.u
. color.u
. devices_var.u
. android.u

function kill_monkey {

    monkey_pid=$(adb -s $device_sn shell ps -A| grep -m 1 -i "monkey"|awk '{print $2}')
    adb -s $device_sn shell kill -9 $monkey_pid
}

trap kill_monkey 2

if [ $os_build_vesion == "userdebug" -o $os_build_vesion == "eng" -o $isROOT = "true" ];then
    adb -s $device_sn shell setprop sys.audio.monkeycontrl 1
fi

monkey_test_start_time=`date "+%Y%m%d%H%M%S"`
logfile_monkey_test=logfile_actions_monkey_test.${monkey_test_start_time}.txt
adb -s $device_sn shell monkey --ignore-crashes --ignore-timeouts --throttle 500 --ignore-security-exceptions --monitor-native-crashes --ignore-native-crashes -s 6516 10000000 > $logfile_monkey_test

if [ $os_build_vesion == "userdebug" -o $os_build_vesion == "eng" -o $isROOT = "true" ];then
    adb -s $device_sn shell setprop sys.audio.monkeycontrl 0
fi

trap : 2
