#!/bin/bash

# $1: logfile
# $2: casename

parseGC_start_time=`date "+%Y%m%d%H%M%S"`
logfile_parseGC=logfile_parseGC.${parseGC_start_time}.txt

grep "GC freed" $1 |awk -F "," '
								/Background sticky concurrent mark sweep/{print "t1",$5}
								/Background partial concurrent mark sweep/{print "t2",$5}
								/CollectorTransition marksweep \+ semispace/{print "t3",$5}
								/Explicit concurrent mark sweep/{print "t4",$5}
								'\
					|awk '{print $1,$3,$5}'\
					|awk '{gsub(/ms/," ms"); gsub(/us/," us"); gsub(/[0-9]s/, " s"); print $0}'\
					|awk '
						{
							if($3=="us"){
								pause=$2/1000;
							} else if($3=="s"){
								pause=$2*1000;
							} else if($3=="ms"){
								pause=$2;
							} 
							
							if($5=="us"){
								total=$4/1000;
							} else if($5=="s"){
								total=$4*1000;
							}else{
								total=$4;
							}
							
							print $1,pause,total;
						}
						' > $logfile_parseGC

python $SCRIPT_ROOT/py/gc2.txt $logfile_parseGC $2
