#!/bin/bash

tmp_file=statics_files.$(date +%s)
ls -l | grep "^d"|awk '{print $9}' > $tmp_file
total_count=0

while read line
do
cd $line;
tmp_count=`ls -lR|grep "^-"|wc -l`
echo "$line: "$tmp_count
total_count=`expr ${total_count} + ${tmp_count}`
cd ..
done < $tmp_file
echo "Total: ${total_count}"

rm $tmp_file