#!/bin/bash

# the first parameter was the application which you want to trace, you can use `pidof xxx` replace it.
function_name=$1

debugfs=/sys/kernel/debug

echo nop > $debugfs/tracing/current_tracer

echo 0 > $debugfs/tracing/tracing_on

#echo `pidof read` > $debugfs/tracing/set_ftrace_pid
echo $function_name > $debugfs/tracing/set_ftrace_pid

echo function_graph > $debugfs/tracing/current_tracer

echo vfs_read > $debugfs/tracing/set_graph_function

echo 1 > $debugfs/tracing/tracing_on
